-- Bu sorguyu Supabase SQL Editor'de çalıştırın
create table user_reports (
  id bigint generated by default as identity primary key,
  phone_number text not null,
  category text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS (Row Level Security) Politikaları (Opsiyonel ama önerilir)
alter table user_reports enable row level security;

-- Herkesin rapor eklemesine izin ver (Anonim erişim)
create policy "Herkes rapor ekleyebilir"
on user_reports for insert
with check (true);

-- Sadece giriş yapmış kullanıcılar (Admin) raporları görebilir
create policy "Sadece adminler raporları görebilir"
on user_reports for select
using (auth.role() = 'authenticated');
