-- 1. Create App Settings Table (Global Config)
CREATE TABLE IF NOT EXISTS app_settings (
  key TEXT PRIMARY KEY,
  value JSONB,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Insert default settings
INSERT INTO app_settings (key, value)
VALUES 
  ('under_attack_mode', 'false'::jsonb),
  ('ai_classification', 'true'::jsonb)
ON CONFLICT (key) DO NOTHING;

-- 2. Create Spam Patterns Table (Junkboy Rules)
CREATE TABLE IF NOT EXISTS spam_patterns (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pattern TEXT NOT NULL,
  type TEXT NOT NULL CHECK (type IN ('KEYWORD', 'REGEX')),
  category TEXT NOT NULL CHECK (category IN ('JUNK', 'PROMOTION', 'TRANSACTION', 'NOTIFICATION', 'GENERAL')),
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 3. Populate Data from Junkboy

-- Turkish Junk Keywords
INSERT INTO spam_patterns (pattern, type, category) VALUES
('kazan', 'KEYWORD', 'JUNK'),
('kazandınız', 'KEYWORD', 'JUNK'),
('hediye', 'KEYWORD', 'JUNK'),
('ödül', 'KEYWORD', 'JUNK'),
('para', 'KEYWORD', 'JUNK'),
('nakit', 'KEYWORD', 'JUNK'),
('bonus', 'KEYWORD', 'JUNK'),
('ücretsiz', 'KEYWORD', 'JUNK'),
('bedava', 'KEYWORD', 'JUNK'),
('çekiliş', 'KEYWORD', 'JUNK'),
('şanslı', 'KEYWORD', 'JUNK'),
('seçildiniz', 'KEYWORD', 'JUNK'),
('tebrikler', 'KEYWORD', 'JUNK'),
('acil', 'KEYWORD', 'JUNK'),
('sınırlı', 'KEYWORD', 'JUNK'),
('fırsat', 'KEYWORD', 'JUNK'),
('indirim', 'KEYWORD', 'JUNK'),
('kredi', 'KEYWORD', 'JUNK'),
('borç', 'KEYWORD', 'JUNK'),
('bahis', 'KEYWORD', 'JUNK'),
('kumar', 'KEYWORD', 'JUNK'),
('casino', 'KEYWORD', 'JUNK'),
('tıkla', 'KEYWORD', 'JUNK'),
('ara', 'KEYWORD', 'JUNK'),
('hemen', 'KEYWORD', 'JUNK'),
('son gün', 'KEYWORD', 'JUNK');

-- English Junk Keywords
INSERT INTO spam_patterns (pattern, type, category) VALUES
('win', 'KEYWORD', 'JUNK'),
('winner', 'KEYWORD', 'JUNK'),
('prize', 'KEYWORD', 'JUNK'),
('free', 'KEYWORD', 'JUNK'),
('cash', 'KEYWORD', 'JUNK'),
('money', 'KEYWORD', 'JUNK'),
('earn', 'KEYWORD', 'JUNK'),
('claim', 'KEYWORD', 'JUNK'),
('urgent', 'KEYWORD', 'JUNK'),
('limited time', 'KEYWORD', 'JUNK'),
('act now', 'KEYWORD', 'JUNK'),
('call now', 'KEYWORD', 'JUNK'),
('click here', 'KEYWORD', 'JUNK'),
('congratulations', 'KEYWORD', 'JUNK'),
('selected', 'KEYWORD', 'JUNK'),
('lucky', 'KEYWORD', 'JUNK'),
('deal', 'KEYWORD', 'JUNK'),
('loan', 'KEYWORD', 'JUNK'),
('debt', 'KEYWORD', 'JUNK'),
('bet', 'KEYWORD', 'JUNK'),
('gambling', 'KEYWORD', 'JUNK');

-- Promotion Keywords
INSERT INTO spam_patterns (pattern, type, category) VALUES
('sale', 'KEYWORD', 'PROMOTION'),
('offer', 'KEYWORD', 'PROMOTION'),
('promotion', 'KEYWORD', 'PROMOTION'),
('special', 'KEYWORD', 'PROMOTION'),
('satış', 'KEYWORD', 'PROMOTION'),
('kampanya', 'KEYWORD', 'PROMOTION'),
('özel', 'KEYWORD', 'PROMOTION'),
('teklif', 'KEYWORD', 'PROMOTION');

-- Transaction Keywords
INSERT INTO spam_patterns (pattern, type, category) VALUES
('bank', 'KEYWORD', 'TRANSACTION'),
('payment', 'KEYWORD', 'TRANSACTION'),
('transfer', 'KEYWORD', 'TRANSACTION'),
('balance', 'KEYWORD', 'TRANSACTION'),
('account', 'KEYWORD', 'TRANSACTION'),
('transaction', 'KEYWORD', 'TRANSACTION'),
('banka', 'KEYWORD', 'TRANSACTION'),
('ödeme', 'KEYWORD', 'TRANSACTION'),
('havale', 'KEYWORD', 'TRANSACTION'),
('bakiye', 'KEYWORD', 'TRANSACTION'),
('hesap', 'KEYWORD', 'TRANSACTION'),
('işlem', 'KEYWORD', 'TRANSACTION'),
('atm', 'KEYWORD', 'TRANSACTION'),
('card', 'KEYWORD', 'TRANSACTION'),
('kart', 'KEYWORD', 'TRANSACTION'),
('withdraw', 'KEYWORD', 'TRANSACTION'),
('deposit', 'KEYWORD', 'TRANSACTION'),
('çekim', 'KEYWORD', 'TRANSACTION'),
('yatırım', 'KEYWORD', 'TRANSACTION');

-- Notification Keywords
INSERT INTO spam_patterns (pattern, type, category) VALUES
('reminder', 'KEYWORD', 'NOTIFICATION'),
('appointment', 'KEYWORD', 'NOTIFICATION'),
('scheduled', 'KEYWORD', 'NOTIFICATION'),
('delivery', 'KEYWORD', 'NOTIFICATION'),
('shipped', 'KEYWORD', 'NOTIFICATION'),
('hatırlatma', 'KEYWORD', 'NOTIFICATION'),
('randevu', 'KEYWORD', 'NOTIFICATION'),
('teslimat', 'KEYWORD', 'NOTIFICATION'),
('kargo', 'KEYWORD', 'NOTIFICATION'),
('gönderildi', 'KEYWORD', 'NOTIFICATION'),
('activation', 'KEYWORD', 'NOTIFICATION'),
('verification', 'KEYWORD', 'NOTIFICATION'),
('code', 'KEYWORD', 'NOTIFICATION'),
('otp', 'KEYWORD', 'NOTIFICATION'),
('aktivasyon', 'KEYWORD', 'NOTIFICATION'),
('doğrulama', 'KEYWORD', 'NOTIFICATION'),
('kod', 'KEYWORD', 'NOTIFICATION');

-- Regex Patterns (Escaped backslashes for SQL string)
INSERT INTO spam_patterns (pattern, type, category) VALUES
('(?i)\\b(win|won|winner)\\s+(\\$|€|₺|prize|ödül)', 'REGEX', 'JUNK'),
('(?i)\\b(para|money|cash)\\s+(kazan|win|earn)', 'REGEX', 'JUNK'),
('(?i)\\b(ücretsiz|free|bedava)\\s+(hediye|gift|bonus)', 'REGEX', 'JUNK'),
('(?i)\\b(çekiliş|lottery|draw)\\s+(kazandınız|won|winner)', 'REGEX', 'JUNK'),
('(?i)\\b(tıkla|click)\\s+(kazan|win|here)', 'REGEX', 'JUNK'),
('(?i)\\b(hemen|urgent|acil)\\s+(ara|call|now)', 'REGEX', 'JUNK'),
('(?i)\\b(son|last|final)\\s+(gün|day|şans|chance)', 'REGEX', 'JUNK'),
('(?i)\\b(kumar|gambling|bahis|bet|casino)', 'REGEX', 'JUNK'),
('(?i)(\\+90|0090)\\s?5\\d{2}\\s?\\d{3}\\s?\\d{2}\\s?\\d{2}', 'REGEX', 'JUNK'),
('(?i)\\b\\d{4}\\s?(tl|₺|usd|eur|€)\\b', 'REGEX', 'JUNK'),
('(?i)\\b(kredi|loan|borç|debt)\\s+(teklif|offer|onay|approval)', 'REGEX', 'JUNK');

-- 4. Enable RLS
ALTER TABLE app_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE spam_patterns ENABLE ROW LEVEL SECURITY;

-- 5. Create Policies (Allow public read, admin write)
-- Note: Assuming authenticated users are admins for simplicity based on previous code
CREATE POLICY "Public Read Settings" ON app_settings FOR SELECT USING (true);
CREATE POLICY "Admin All Settings" ON app_settings FOR ALL USING (auth.role() = 'authenticated');

CREATE POLICY "Public Read Patterns" ON spam_patterns FOR SELECT USING (true);
CREATE POLICY "Admin All Patterns" ON spam_patterns FOR ALL USING (auth.role() = 'authenticated');
