-- user_reports tablosuna yeni kolonlar ekleme
alter table user_reports 
add column if not exists comment text,
add column if not exists reporter_name text default 'Misafir Kullanıcı';

-- Eğer tablo yoksa baştan oluşturma (Güvenlik için)
create table if not exists user_reports (
  id bigint generated by default as identity primary key,
  phone_number text not null,
  category text not null,
  comment text,
  reporter_name text default 'Misafir Kullanıcı',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS Politikalarını Güncelleme (Herkes okuyabilsin diye)
alter table user_reports enable row level security;

create policy "Herkes raporları görebilir"
on user_reports for select
using (true);

create policy "Herkes rapor ekleyebilir"
on user_reports for insert
with check (true);

create policy "Sadece admin silebilir"
on user_reports for delete
using (auth.role() = 'authenticated');
